### ISSUE TITLE
编译总是报错

### ISSUE THREAD

**Issue by yuzhongrong** [F-loat/ChineseBQB-client#2]
![image](https://user-images.githubusercontent.com/7382234/118657424-0d80b300-b81e-11eb-8375-ec227bb23b8b.png)

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/118657835-68b2a580-b81e-11eb-800b-41b179d167aa.png)

**Comment by yuzhongrong** [comment]
why?

**Comment by F-loat** [comment]
好像是 taro 新版的构建配置有变化，有空了我更新下

**Comment by F-loat** [comment]
已修复
